### ISSUE TITLE
problem in lp14.cpp

### ISSUE THREAD

**Issue by Amanskywalker** [Amanskywalker/ds-lab-programs#1]
it is displaying same output for preorder and inorder. Try to rectify it. 
1. Insert
2. Display
3. Exit
   Enter choice
   :1
   Enter number    :4
4. Insert
5. Display
6. Exit
   Enter choice
   :1
   Enter number    :5
7. Insert
8. Display
9. Exit
   Enter choice
   :1
   Enter number    :6
10. Insert
11. Display
12. Exit
    Enter choice
    :2

Preorder    4   5   6  
Inorder     4   5   6  
Postorder   6   5   4  
1. Insert
2. Display
3. Exit
 Enter choice
:

pre and in order are same 

in should be  5  4  6

**Comment by dhanyamkashyap** [comment]
#include<iostream>

using namespace std;

struct node
{
    int info;
    struct node *left;
    struct node *right;
};

typedef struct node tree;

tree *root=NULL;

class Bin
{
    int num;
    tree _prev,_p,_temp;
    public:
    void insert();
    void preorder(tree_);
    void inorder(tree_);
    void postorder(tree_);
    void display();
};

void Bin::insert()
{
    p=new (tree);
    cout<<"Enter number\t:";
    cin>>num;
    p->info=num;
    p->left=p->right=NULL;
    if(root==NULL)
    {
        root=p;
        return;
    }
    temp=root;
    while(temp!=NULL)
    {     //here the while loop starts
        if(num>=temp->info)
        {
            prev=temp;
            temp=temp->right;
        }
        else
        {
            prev=temp;
            temp=temp->left;
        }
    if(num>=prev->info)
    {
        prev->right=p;
    }
    else
    {
        prev->left=p;
    }
} //here it ends
}

void Bin::preorder(tree *temp)
{
    if(temp!=NULL)
    {
        cout<<temp->info<<"\t";
        preorder(temp->left);
        preorder(temp->right);
    }
}

void Bin::inorder(tree *temp)
{
    if(temp!=NULL)
    {
        inorder(temp->left);
        cout<<temp->info<<"\t";
        inorder(temp->right);
    }
}

void Bin::postorder(tree *temp)
{
    if(temp!=NULL)
    {
        postorder(temp->left);
        postorder(temp->right);
        cout<<temp->info<<"\t";
    }
}

void Bin::display()
{
    if(root==NULL)
    {
        cout<<"Tree is empty";
        return;
    }
    cout<<"\nPreorder \t";preorder(root);
    cout<<"\nInorder  \t";inorder(root);
    cout<<"\nPostorder\t";postorder(root);
}

int main()
{
    Bin ob;
    int ch;
    while(true)
    {
        cout<<"\n1. Insert\n2. Display\n3. Exit\n Enter choice\n:";
        cin>>ch;
        switch(ch)
        {
            case 1:ob.insert();
                    break;
            case 2:ob.display();
                    break;
            case 3:return 0;
        }
    }
    return 0;
}

**Comment by Amanskywalker** [comment]
1. Insert
2. Display
3. Exit
   Enter choice
   :1
   Enter number    :4
4. Insert
5. Display
6. Exit
   Enter choice
   :1
   Enter number    :5
7. Insert
8. Display
9. Exit
   Enter choice
   :1
   Enter number    :6
10. Insert
11. Display
12. Exit
    Enter choice
    :2

Preorder    4   6  
Inorder     4   6  
Postorder   6   4  
1. Insert
2. Display
3. Exit
 Enter choice
:

now left node is missing

**Comment by dhanyamkashyap** [comment]
because its overwriting values on right node if u have entered two values greater than 4...try entering one value less than root node and one greater than root node

**Comment by Amanskywalker** [comment]
all right issue have been resolved
